# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: G. Beau McFarland
email: gbeaumcfarland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  G. Beau McFarland is an American stand-up comic, writer, 
  actor, and Nutella-lover, originally from Southern California.
url: "http://gbeaumcfarland.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
